### PR TITLE
fix the Spring Boot release notes link anchor

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by Ladicek** [comment]
Sorry, this was too easy to fix so I didn't bother to create an issue :-)

**Comment by rhoads-zach** [comment]
merged: e095fd284d7162eb1eb526d50d409d14324edeed

**Comment by rhoads-zach** [comment]
FYI @Ladicek i had to adapt this PR since some of this content was moved around in an earlier PR that was queued up.

**Comment by Ladicek** [comment]
Thanks @lavernw1 & @rhoads-zach!

**Pull request closed without merging**
